### ISSUE TITLE
Can't mark green spheres as rings

### ISSUE THREAD

**Issue by funcmathias** [MainMemory/ManiaBSEdit#1]
Seem to not be able mark green spheres as rings, can do it if you override a blue sphere that's marked as a ring with a green sphere, then save and re-open the file.

**Comment by funcmathias** [comment]
Note: The blue sphere marked as ring you override has to be there when the file was opened, if done in the same session the green sphere will not gain the ring attribute when saved and opened again.

**Comment by MainMemory** [comment]
The fact that you can't mark green spheres as rings is an oversight, but the fact that replacing marked blue spheres keeps them marked is a bug.
