### ISSUE TITLE
Error when launching with grid off

### ISSUE THREAD

**Issue by funcmathias** [MainMemory/ManiaBSEdit#3]
If ShowGrid is set to False on launch the application will get an error and not be able to launch, changing it to True manually allows it to launch again.

**Comment by MainMemory** [comment]
Just a tip for the future: it's considered polite to include as much detail as you can when reporting errors, such as the details from the exception dialog, so that I can more quickly identify the source of the problem.

**Comment by funcmathias** [comment]
Sorry just figured it was a very easy one to replicate, will include every time then.
